# Generated by Django 3.1.4 on 2020-12-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
